### PR TITLE
Infinite autosculpt slider

### PR DESCRIPTION
**Pull request by Frouk3**
I decided to bring back this function since i've seen that someone opened an issue because infinite autosculpt slider was removed

### CODE REVIEW

**Comment by Frouk3** [comment]
@nlgxzef Hello, are you there or you are dead?

**Comment by nlgxzef** [comment]
The feature is implemented in a test build and will be available for everyone with the next public release. Thanks for your help!

_Note: The pull request didn't get merged beacuse the test build contains reorganized and more recent code._

**Comment by Frouk3** [comment]
> The feature is implemented in a test build and will be available for everyone with the next public release. Thanks for your help!
> 
> _Note: The pull request didn't get merged beacuse the test build contains reorganized and more recent code._

also i forgot to mention, this bypass applies for all sliders
means that some values can be overwritten into a bigger

**Comment by nlgxzef** [comment]
The new implementation of the feature only affects Autosculpt sliders.

**Comment by Frouk3** [comment]
Oh, that's good

And code compares value with auto sculpture value and makes changes if so?

**Comment by nlgxzef** [comment]
No, we have reimplemented some functions in the FESliderWidget class.

**Comment by Frouk3** [comment]
also i wanted to contact you, but you off the your dms

**Pull request closed without merging**
